name: Feature Request
description: Suggest a feature for this library
labels: ["feature request"]
body:
  - type: input
    attributes:
      label: Summary
      description: >
        A short summary of what your feature request is.
    validations:
      required: true
  - type: dropdown
    attributes:
      multiple: false
      label: What is the feature request for?
      options:
        - nextcord.ext.help_commands
        - The documentation
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: >
        What is the problem and your ideal solution to the problem?
        What would you like this feature to do?
    validations:
      required: true
